# Form implementation generated from reading ui file 'c:\Users\victo\OneDrive\Escritorio\UPIITA\4 semestre\programacion avanzada\programas\segundo parcial\practica 7\PRACTICA_07-2\Casa.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(579, 305)
        self.btn_abrirP = QtWidgets.QPushButton(parent=Form)
        self.btn_abrirP.setGeometry(QtCore.QRect(50, 80, 75, 24))
        self.btn_abrirP.setObjectName("btn_abrirP")
        self.btn_cerrarP = QtWidgets.QPushButton(parent=Form)
        self.btn_cerrarP.setGeometry(QtCore.QRect(50, 120, 75, 24))
        self.btn_cerrarP.setObjectName("btn_cerrarP")
        self.btn_encenderF = QtWidgets.QPushButton(parent=Form)
        self.btn_encenderF.setGeometry(QtCore.QRect(210, 80, 75, 24))
        self.btn_encenderF.setObjectName("btn_encenderF")
        self.btn_ApagarF = QtWidgets.QPushButton(parent=Form)
        self.btn_ApagarF.setGeometry(QtCore.QRect(210, 120, 75, 24))
        self.btn_ApagarF.setObjectName("btn_ApagarF")
        self.btn_cortina1 = QtWidgets.QPushButton(parent=Form)
        self.btn_cortina1.setGeometry(QtCore.QRect(330, 80, 75, 24))
        self.btn_cortina1.setObjectName("btn_cortina1")
        self.btn_tendedero2 = QtWidgets.QPushButton(parent=Form)
        self.btn_tendedero2.setGeometry(QtCore.QRect(320, 120, 75, 24))
        self.btn_tendedero2.setObjectName("btn_tendedero2")
        self.btn_reproducirM = QtWidgets.QPushButton(parent=Form)
        self.btn_reproducirM.setGeometry(QtCore.QRect(450, 80, 75, 24))
        self.btn_reproducirM.setObjectName("btn_reproducirM")
        self.btn_detenerM = QtWidgets.QPushButton(parent=Form)
        self.btn_detenerM.setGeometry(QtCore.QRect(440, 120, 75, 24))
        self.btn_detenerM.setObjectName("btn_detenerM")
        self.btn_reiniciarM = QtWidgets.QPushButton(parent=Form)
        self.btn_reiniciarM.setGeometry(QtCore.QRect(440, 160, 75, 24))
        self.btn_reiniciarM.setObjectName("btn_reiniciarM")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_abrirP.setText(_translate("Form", "Abrir"))
        self.btn_cerrarP.setText(_translate("Form", "PushButton"))
        self.btn_encenderF.setText(_translate("Form", "encender"))
        self.btn_ApagarF.setText(_translate("Form", "PushButton"))
        self.btn_cortina1.setText(_translate("Form", "tendedero1"))
        self.btn_tendedero2.setText(_translate("Form", "tendedero2"))
        self.btn_reproducirM.setText(_translate("Form", "Reproducir"))
        self.btn_detenerM.setText(_translate("Form", "detener"))
        self.btn_reiniciarM.setText(_translate("Form", "reiniciar"))
