# Form implementation generated from reading ui file 'c:\Users\toshiba\Desktop\Programacion\Pyton\Practica 7\PRACTICA_07\PRACTICA_07-1\Grupos.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Grupo(object):
    def setupUi(self, Grupo):
        Grupo.setObjectName("Grupo")
        Grupo.resize(900, 600)
        Grupo.setMinimumSize(QtCore.QSize(900, 600))
        Grupo.setMaximumSize(QtCore.QSize(900, 600))
        self.msgView = QtWidgets.QPlainTextEdit(parent=Grupo)
        self.msgView.setGeometry(QtCore.QRect(285, 155, 580, 300))
        self.msgView.setMinimumSize(QtCore.QSize(580, 300))
        self.msgView.setMaximumSize(QtCore.QSize(580, 300))
        self.msgView.setReadOnly(True)
        self.msgView.setObjectName("msgView")
        self.msgWrite = QtWidgets.QLineEdit(parent=Grupo)
        self.msgWrite.setGeometry(QtCore.QRect(285, 461, 500, 25))
        self.msgWrite.setMinimumSize(QtCore.QSize(500, 25))
        self.msgWrite.setMaximumSize(QtCore.QSize(580, 400))
        self.msgWrite.setObjectName("msgWrite")
        self.msgSend = QtWidgets.QPushButton(parent=Grupo)
        self.msgSend.setGeometry(QtCore.QRect(790, 460, 75, 27))
        self.msgSend.setMinimumSize(QtCore.QSize(75, 27))
        self.msgSend.setMaximumSize(QtCore.QSize(580, 400))
        self.msgSend.setObjectName("msgSend")
        self.btn_profilePicture = QtWidgets.QPushButton(parent=Grupo)
        self.btn_profilePicture.setGeometry(QtCore.QRect(50, 80, 180, 180))
        self.btn_profilePicture.setMinimumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture.setMaximumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\toshiba\\Desktop\\Programacion\\Pyton\\Practica 7\\PRACTICA_07\\PRACTICA_07-1\\../Practica 7/Icons/Icon_Fish.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_profilePicture.setIcon(icon)
        self.btn_profilePicture.setIconSize(QtCore.QSize(165, 165))
        self.btn_profilePicture.setObjectName("btn_profilePicture")
        self.listWidget = QtWidgets.QListWidget(parent=Grupo)
        self.listWidget.setGeometry(QtCore.QRect(20, 330, 230, 220))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.userName = QtWidgets.QLabel(parent=Grupo)
        self.userName.setGeometry(QtCore.QRect(285, 110, 580, 40))
        self.userName.setMinimumSize(QtCore.QSize(370, 40))
        self.userName.setMaximumSize(QtCore.QSize(580, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.userName.setFont(font)
        self.userName.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userName.setObjectName("userName")
        self.userName_2 = QtWidgets.QLabel(parent=Grupo)
        self.userName_2.setGeometry(QtCore.QRect(20, 280, 230, 40))
        self.userName_2.setMinimumSize(QtCore.QSize(50, 40))
        self.userName_2.setMaximumSize(QtCore.QSize(580, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.userName_2.setFont(font)
        self.userName_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userName_2.setObjectName("userName_2")
        self.btn_Close = QtWidgets.QPushButton(parent=Grupo)
        self.btn_Close.setGeometry(QtCore.QRect(790, 530, 75, 24))
        self.btn_Close.setObjectName("btn_Close")

        self.retranslateUi(Grupo)
        QtCore.QMetaObject.connectSlotsByName(Grupo)

    def retranslateUi(self, Grupo):
        _translate = QtCore.QCoreApplication.translate
        Grupo.setWindowTitle(_translate("Grupo", "Form"))
        self.msgSend.setText(_translate("Grupo", "Enviar"))
        self.userName.setText(_translate("Grupo", "Name_Group"))
        self.userName_2.setText(_translate("Grupo", "Activos"))
        self.btn_Close.setText(_translate("Grupo", "Cerrar"))
