# Form implementation generated from reading ui file 'c:\Users\victo\OneDrive\Escritorio\UPIITA\4 semestre\programacion avanzada\programas\segundo parcial\practica 7\PRACTICA_07\Primera.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogPrim(object):
    def setupUi(self, DialogPrim):
        DialogPrim.setObjectName("DialogPrim")
        DialogPrim.resize(453, 397)
        DialogPrim.setMinimumSize(QtCore.QSize(453, 397))
        DialogPrim.setMaximumSize(QtCore.QSize(453, 397))
        self.label_3 = QtWidgets.QLabel(parent=DialogPrim)
        self.label_3.setGeometry(QtCore.QRect(220, 30, 49, 16))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=DialogPrim)
        self.label_4.setGeometry(QtCore.QRect(140, 40, 191, 151))
        self.label_4.setStyleSheet("border-image: url(:/imagen_sesion/imagen_inicio_sesion.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.layoutWidget = QtWidgets.QWidget(parent=DialogPrim)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 200, 204, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Usuario = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Usuario.setObjectName("Usuario")
        self.horizontalLayout.addWidget(self.Usuario)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Contra = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.Contra.setObjectName("Contra")
        self.horizontalLayout_2.addWidget(self.Contra)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn1 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn1.setObjectName("btn1")
        self.verticalLayout.addWidget(self.btn1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.btn2 = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn2.setObjectName("btn2")
        self.verticalLayout_2.addWidget(self.btn2)

        self.retranslateUi(DialogPrim)
        QtCore.QMetaObject.connectSlotsByName(DialogPrim)

    def retranslateUi(self, DialogPrim):
        _translate = QtCore.QCoreApplication.translate
        DialogPrim.setWindowTitle(_translate("DialogPrim", "Dialog"))
        self.label.setText(_translate("DialogPrim", "Usuario"))
        self.label_2.setText(_translate("DialogPrim", "Contraseña"))
        self.btn1.setText(_translate("DialogPrim", "Iniciar sesion"))
        self.btn2.setText(_translate("DialogPrim", "Nuevo usuario"))
