# Form implementation generated from reading ui file '/home/ja/OneDrive/Documentos/4to_semestre/PA/Practica_07/msn_v1_project/Primera.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DialogPrim(object):
    def setupUi(self, DialogPrim):
        DialogPrim.setObjectName("DialogPrim")
        DialogPrim.resize(619, 800)
        self.btn1 = QtWidgets.QPushButton(parent=DialogPrim)
        self.btn1.setGeometry(QtCore.QRect(220, 250, 75, 24))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(parent=DialogPrim)
        self.btn2.setGeometry(QtCore.QRect(304, 250, 81, 24))
        self.btn2.setObjectName("btn2")
        self.label = QtWidgets.QLabel(parent=DialogPrim)
        self.label.setGeometry(QtCore.QRect(130, 70, 141, 71))
        self.label.setObjectName("label")

        self.retranslateUi(DialogPrim)
        QtCore.QMetaObject.connectSlotsByName(DialogPrim)

    def retranslateUi(self, DialogPrim):
        _translate = QtCore.QCoreApplication.translate
        DialogPrim.setWindowTitle(_translate("DialogPrim", "Dialog"))
        self.btn1.setText(_translate("DialogPrim", "Siguiente"))
        self.btn2.setText(_translate("DialogPrim", "Ir a Segunda"))
        self.label.setText(_translate("DialogPrim", "Primera xD"))
