# Form implementation generated from reading ui file 'c:\Users\toshiba\Desktop\Programacion\Pyton\Practica 7\PRACTICA_07\PRACTICA_07-1\Privado.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Privado(object):
    def setupUi(self, Privado):
        Privado.setObjectName("Privado")
        Privado.resize(900, 600)
        Privado.setMinimumSize(QtCore.QSize(900, 600))
        Privado.setMaximumSize(QtCore.QSize(900, 600))
        self.msgView = QtWidgets.QPlainTextEdit(parent=Privado)
        self.msgView.setGeometry(QtCore.QRect(285, 155, 580, 300))
        self.msgView.setMinimumSize(QtCore.QSize(580, 300))
        self.msgView.setMaximumSize(QtCore.QSize(580, 300))
        self.msgView.setObjectName("msgView")
        self.msgWrite = QtWidgets.QLineEdit(parent=Privado)
        self.msgWrite.setGeometry(QtCore.QRect(285, 461, 500, 25))
        self.msgWrite.setMinimumSize(QtCore.QSize(500, 25))
        self.msgWrite.setMaximumSize(QtCore.QSize(580, 400))
        self.msgWrite.setObjectName("msgWrite")
        self.msgSend = QtWidgets.QPushButton(parent=Privado)
        self.msgSend.setGeometry(QtCore.QRect(790, 460, 75, 27))
        self.msgSend.setMinimumSize(QtCore.QSize(75, 27))
        self.msgSend.setMaximumSize(QtCore.QSize(580, 400))
        self.msgSend.setObjectName("msgSend")
        self.btn_profilePicture = QtWidgets.QPushButton(parent=Privado)
        self.btn_profilePicture.setGeometry(QtCore.QRect(50, 80, 180, 180))
        self.btn_profilePicture.setMinimumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture.setMaximumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\toshiba\\Desktop\\Programacion\\Pyton\\Practica 7\\PRACTICA_07\\PRACTICA_07-1\\../Practica 7/Icons/Icon_Fish.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_profilePicture.setIcon(icon)
        self.btn_profilePicture.setIconSize(QtCore.QSize(165, 165))
        self.btn_profilePicture.setObjectName("btn_profilePicture")
        self.btn_profilePicture_2 = QtWidgets.QPushButton(parent=Privado)
        self.btn_profilePicture_2.setGeometry(QtCore.QRect(50, 350, 180, 180))
        self.btn_profilePicture_2.setMinimumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture_2.setMaximumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture_2.setText("")
        self.btn_profilePicture_2.setIcon(icon)
        self.btn_profilePicture_2.setIconSize(QtCore.QSize(165, 165))
        self.btn_profilePicture_2.setObjectName("btn_profilePicture_2")
        self.widget = QtWidgets.QWidget(parent=Privado)
        self.widget.setGeometry(QtCore.QRect(700, 520, 163, 26))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Privado)
        QtCore.QMetaObject.connectSlotsByName(Privado)

    def retranslateUi(self, Privado):
        _translate = QtCore.QCoreApplication.translate
        Privado.setWindowTitle(_translate("Privado", "Form"))
        self.msgSend.setText(_translate("Privado", "Enviar"))
        self.pushButton.setText(_translate("Privado", "Jugar"))
        self.pushButton_2.setText(_translate("Privado", "Cerrar"))
