# Form implementation generated from reading ui file 'c:\Users\Osvaldo Flores\Desktop\Cuarto Semestre UPIITA\Programacion Avanzada\PRACTICA_07-4\Privado.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Privado(object):
    def setupUi(self, Privado):
        Privado.setObjectName("Privado")
        Privado.resize(900, 600)
        Privado.setMinimumSize(QtCore.QSize(900, 600))
        Privado.setMaximumSize(QtCore.QSize(900, 600))
        self.msgViewPrivate = QtWidgets.QPlainTextEdit(parent=Privado)
        self.msgViewPrivate.setGeometry(QtCore.QRect(285, 155, 580, 300))
        self.msgViewPrivate.setMinimumSize(QtCore.QSize(580, 300))
        self.msgViewPrivate.setMaximumSize(QtCore.QSize(580, 300))
        self.msgViewPrivate.setReadOnly(True)
        self.msgViewPrivate.setObjectName("msgViewPrivate")
        self.msgWritePrivate = QtWidgets.QLineEdit(parent=Privado)
        self.msgWritePrivate.setGeometry(QtCore.QRect(285, 461, 500, 25))
        self.msgWritePrivate.setMinimumSize(QtCore.QSize(500, 25))
        self.msgWritePrivate.setMaximumSize(QtCore.QSize(580, 400))
        self.msgWritePrivate.setObjectName("msgWritePrivate")
        self.msgSendPrivate = QtWidgets.QPushButton(parent=Privado)
        self.msgSendPrivate.setGeometry(QtCore.QRect(790, 460, 75, 27))
        self.msgSendPrivate.setMinimumSize(QtCore.QSize(75, 27))
        self.msgSendPrivate.setMaximumSize(QtCore.QSize(580, 400))
        self.msgSendPrivate.setObjectName("msgSendPrivate")
        self.btn_friendPicture = QtWidgets.QPushButton(parent=Privado)
        self.btn_friendPicture.setGeometry(QtCore.QRect(50, 40, 180, 180))
        self.btn_friendPicture.setMinimumSize(QtCore.QSize(180, 180))
        self.btn_friendPicture.setMaximumSize(QtCore.QSize(180, 180))
        self.btn_friendPicture.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Osvaldo Flores\\Desktop\\Cuarto Semestre UPIITA\\Programacion Avanzada\\PRACTICA_07-4\\../Practica 7/Icons/Icon_Fish.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_friendPicture.setIcon(icon)
        self.btn_friendPicture.setIconSize(QtCore.QSize(165, 165))
        self.btn_friendPicture.setObjectName("btn_friendPicture")
        self.btn_profilePicture = QtWidgets.QPushButton(parent=Privado)
        self.btn_profilePicture.setGeometry(QtCore.QRect(50, 350, 180, 180))
        self.btn_profilePicture.setMinimumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture.setMaximumSize(QtCore.QSize(180, 180))
        self.btn_profilePicture.setText("")
        self.btn_profilePicture.setIcon(icon)
        self.btn_profilePicture.setIconSize(QtCore.QSize(165, 165))
        self.btn_profilePicture.setObjectName("btn_profilePicture")
        self.layoutWidget = QtWidgets.QWidget(parent=Privado)
        self.layoutWidget.setGeometry(QtCore.QRect(700, 520, 163, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Play = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_Play.setObjectName("btn_Play")
        self.horizontalLayout.addWidget(self.btn_Play)
        self.btn_Close = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_Close.setObjectName("btn_Close")
        self.horizontalLayout.addWidget(self.btn_Close)
        self.userName = QtWidgets.QLabel(parent=Privado)
        self.userName.setGeometry(QtCore.QRect(270, 40, 381, 40))
        self.userName.setMinimumSize(QtCore.QSize(370, 40))
        self.userName.setMaximumSize(QtCore.QSize(580, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.userName.setFont(font)
        self.userName.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.userName.setObjectName("userName")

        self.retranslateUi(Privado)
        QtCore.QMetaObject.connectSlotsByName(Privado)

    def retranslateUi(self, Privado):
        _translate = QtCore.QCoreApplication.translate
        Privado.setWindowTitle(_translate("Privado", "Form"))
        self.msgSendPrivate.setText(_translate("Privado", "Enviar"))
        self.btn_Play.setText(_translate("Privado", "Jugar"))
        self.btn_Close.setText(_translate("Privado", "Cerrar"))
        self.userName.setText(_translate("Privado", "Name_Friend"))
